### ISSUE TITLE
format error in opening_hours

### ISSUE THREAD

**Issue by Popolon** [Helium314/StreetComplete#581] opened 2024-07-09 14:13 UTC
**How to Reproduce**

add several days in opening hours

**Expected Behavior**

After Open Street Map documentation, days are separated by ";" and hours ranges by ",", But in SCEE, days are separated by ",".

https://wiki.openstreetmap.org/wiki/Key:opening_hours#Multiple_days_and_multiple_time_periods

**Does it happen in normal StreetComplete?**

Street Complete fill this field correctly, with days separated by ";"

**Versions affected**

SCEE 58.1 from F-Droid

**Comment by cayenne17** [comment] 2024-07-09 15:13
On version 3 of the [737541281](https://www.openstreetmap.org/node/737541281/history/3) node, in the modification group, it is `StreetComplete_ee 53.32`.

The problem was already there before

**Comment by mnalis** [comment] 2024-07-09 15:13
(I have not look up into it deeper yet), but note that **both** `;` and `,` are valid separators for `opening_hours`, and their function differs. See https://wiki.openstreetmap.org/wiki/Key:opening_hours#Closing_after_midnight for details

Can you confirm that **for exactly the same time range** SCEE and StreetComplete output differs? (please give example)

**Comment by Popolon** [comment] 2024-07-09 15:49
Their function differ as I said, the , is used between time ranges in the same day. As I said, I tried with StreetComplete and the output was correct. I use last StreeteCompte v58.1 from F-Droid.

Someona send me this screenshot from JOSM, that complains about this wrong format he see time to time, and comfirmed by tags of an example that it was added using StreetComplete_EE.
![JOSM_error](https://github.com/Helium314/SCEE/assets/5034852/a7bf590c-e5cb-48ed-a7ca-745afa89002d)

**Comment by Popolon** [comment] 2024-07-09 15:54
Ah, sorry, didn't read well the last link, I understand now, I only entered opening hour in day time in my StreetComplete test, could be linked.

**Comment by Popolon** [comment] 2024-07-09 16:11
One of the entries where I found a "," instead of a ";" is:
`Mo-Sa 16:00-02:00; Su 17:00-02:00`
So it's not linked to past midnight case with ","

**Comment by mnalis** [comment] 2024-07-09 19:20
Yes, `;` **resets any information** already present for that day. `,` does not.

You can check at https://openingh.openstreetmap.de/evaluation_tool/ how it behaves.

- In your example `Mo-Sa 16:00-02:00; Su 17:00-02:00` means (somewhat counterintuitively) that at Sunday at 1:00 am it will be **closed**.

- However `Mo-Sa 16:00-02:00, Su 17:00-02:00` works as expected (i.e. the place is **open** at Sunday 1:00 am)

In other words, if place is **open over midnight**, you must use `,` instead of `;` to separate days to get "logical" results, or alternatively you must change your opening hours to never cross midnight (e.g. `Mo-Sa 00:00-02:00,16:00-24:00; Su 00:00-02:00,17:00-24:00` - but using `,` to separate days is usually much simpler and easier to understand)
 
----

That's why I asked if you tested with exactly the same time range in StreetComplete as you did in SCEE. 
I suspect that for same opening hours both StreetComplete and SCEE will mark place with same `opening_hours` tag.

Can you @Popolon  check / confirm if that is the case and both StreetComplete and SCEE tag the same values (when given same time ranges)?

**Comment by mnalis** [comment] 2024-07-09 19:36
> Someona send me this screenshot from JOSM, that complains about this wrong format he see time to time, and comfirmed by tags of an example that it was added using StreetComplete_EE.
![JOSM_error](https://github.com/Helium314/SCEE/assets/5034852/a7bf590c-e5cb-48ed-a7ca-745afa89002d)

Interesting, that validation error does not occur for me in JOSM (10967) when trying to upload `opening_hours` with value `Tu-Fr,Su 07:30-13:30, Tu,Th-Sa 16:00-18:30`. Also https://openingh.openstreetmap.de/evaluation_tool/ (which is the best tool for checking OSM `opening_hours`) does not complain about it. 

I would guess your friend uses some external JOSM validator (`F12` / `Data validator` / `Tag checker rules` ?), and that this external validator has a bug if it complains about that specific time format. They should report in to validator author so it can be fixed there so valid `opening_hours` formats are accepted.

**Comment by Popolon** [comment] 2024-07-09 22:50
The , instead if ; is put by SCEE in the exemple I given, I replaced it by ; myself

This syntax put by SCEE:
`Mo-Sa 16:00-02:00, Su 17:00-02:00`
Would mean a continuous day, this is not the case and would be worst in case where there is it's closed saturday for example.

However, this syntax is valid:
`Mo-Sa 16:00-02:00; Su 17:00-02:00`
As said here:
https://wiki.openstreetmap.org/wiki/Key:opening_hours#Closing_after_midnight

<p>In some cases places are closing after midnight. For example place 
opening on Monday at 20:00 and closing after midnight, at 2:00 can be 
marked in following ways - which are all valid, according to <a href="https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification" title="Key:opening hours/specification">specification</a>:
</p>

opening_hours= Mo 20:00-26:00
--
Open on Monday at 20:00, closed 2:00 — using extended hour syntax

In some cases places are closing after midnight. For example place opening on Monday at 20:00 and closing after midnight, at 2:00 can be marked in following ways - which are all valid, according to [specification](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification):
opening_hours= Mo 20:00-26:00
Open on Monday at 20:00, closed 2:00 — using [extended hour syntax](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#extended_hour)
opening_hours= Mo 20:00-02:00
Open on Monday at 20:00, closed 2:00 — using [extended hour syntax](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:extended_hour_minutes)

**Comment by mnalis** [comment] 2024-07-10 02:36
Uh, you seem to be saying exactly as I did, or am I missing something? 

If you still thing there is an issue with SCEE @Popolon , can you please do the following (preferably after disabling auto-upload, as to not pollute the OSM database with tests):
1. provide screenshot of SCEE showing what days/times you have selected
2. provide screenshot of SCEE undo button showing what SCEE tagged
3. provide screenshot of StreetComplete showing what days/times you have selected (for those same timeranges as in `1.`!)
4. provide screenshot of StreetComplete undo button showing what StreetComplete tagged

<Details>

<summary>Those 4 screenshots would allow us to:</summary>

- avoid confusion / misunderstandings what case we are talking about exactly
- verify whether SCEE and StreetComplete behave the same (if they do, any bug report should probably be reported to upstream StreetComplete instead - as the problem then is in StreetComplete code, and not SCEE modifications. Or, alternatively, reasoning could be provided why one thinks SCEE should behave differently than StreetComplete) 
- verify whether the produced `opening_hours` tagging is correct, i.e. whether the issue is:
  - actual incorrect tagging, or
  - confusing SC(EE) UI, or 
  - confusing `opening_hours` syntax

</details>

---

Here is my example how it looks in SCEE (steps `1.` and `2.`):
![small_Screenshot_20240710_040031_SCEE](https://github.com/Helium314/SCEE/assets/156656/e28a4c17-5572-4f06-b8ae-8771396ef0ae) ![small_Screenshot_20240710_040049_SCEE](https://github.com/Helium314/SCEE/assets/156656/dc758191-1b2a-4e90-9220-03692e173255)

and I am getting the **same results** in StreetComplete (steps `3.` and `4.`) (so no need for separate screenshots)

In my understanding in that particular case I'd conclude that:
- both SCEE 58.0 and StreetComplete 58.1 produce **same** `opening_hours` tag for that over-midnight case (with `,` separating days)
- that `opening_hours` is **correct tagging**  (as verified by https://openingh.openstreetmap.de/evaluation_tool/), i.e. as I would expect it (e.g. that the place is **open** on Sunday at 1am).

But your example might be different and produce different conclusion!

**Comment by HolgerJeromin** [comment] 2024-07-10 16:12
~~Ref https://github.com/streetcomplete/StreetComplete/issues/773#issuecomment-357799074~~

**Comment by westnordost** [comment] 2024-07-10 18:22
Thanks for the link, but that comment is outdated. No longer does StreetComplete always use the comma operator.

The "magic" that decides in StreetComplete whether to use `,` or `;` as a rule separator is here:

https://github.com/streetcomplete/StreetComplete/blob/fa538aaf983bc32559e8cc6f682fdbe10dd0133c/app/src/main/java/de/westnordost/streetcomplete/osm/opening_hours/parser/OpeningHoursGenerator.kt#L121-L123

The comment explains it:

> if any rule collides with another, e.g. "Mo-Fr 10:00-12:00; We 14:00-16:00", switch to additive rules e.g. "Mo-Fr 10:00-12:00, We 14:00-16:00"

Compare these two opening hours strings in https://openingh.openstreetmap.de/evaluation_tool/ to learn the difference in meaning.

**Comment by westnordost** [comment] 2024-07-10 18:27
I checked if there are any modifications done on that file in SCEE as opposed to StreetComplete and it doesn't look like it, so I am taking the liberty of closing this as not a bug. If you should find that this behavior is erronous in some cases after all, please open an issue directly in STreetComplete (after checking that indeed it can be reproduced in StreetComplete, too)

**Closed as not planned by westnordost** 2024-07-10 18:27 UTC
