### ISSUE TITLE
Set phone:signed=no/website:singed=no

### ISSUE THREAD

**Issue by tiptoptom** [Helium314/StreetComplete#367] opened 2022-05-06 06:49 UTC
What do you think about adding a "not singed" answers option like at the opening_hours quest for the phone and website quest?

**Comment by Helium314** [comment] 2022-05-06 17:58
Well, there is [`phone:signed`](https://taginfo.openstreetmap.org/keys/?key=phone:signed#chronology), which looks like it was used by one user for a short time.
I fear using this could end in spamming `phone:signed=no` all over the place, and this not really useful (other than preventing the quest from showing up) as this tag is not used by (almost) anyone/anything else.

I guess you would like this answer as an alternative to hiding the quest? Quests like this, that are sometimes not answerable, are actually why the quick-hide button was implemented.

**Comment by tiptoptom** [comment] 2022-05-09 16:58
> I guess you would like this answer as an alternative to hiding the quest?

Yes, an alternative to hiding the quest would be nice, because the hiding is only stored locally and others continue to get the quests displayed. (for example my buddy)

An alternative solution might be an import/export facility, though I have no idea how feasible that is.

> Quests like this, that are sometimes not answerable, are actually why the quick-hide button was implemented.

BTW: I know the quick-hide button but on my device the on-screen navigation buttons are above the quick-hide button so I can't use it. =)

**Comment by Helium314** [comment] 2022-05-09 17:04
> BTW: I know the quick-hide button but on my device the on-screen navigation buttons are above the quick-hide button so I can't use it. =)

Oh... I still have a device with buttons, so I wasn't even aware this might be happening. Will try to fix it.

**Comment by tiptoptom** [comment] 2022-05-09 18:17
> Oh... I still have a device with buttons, so I wasn't even aware this might be happening. Will try to fix it.

I thought so :joy:. Thank you :pray:

**Comment by Helium314** [comment] 2022-05-10 05:22
This is weird... the button is basically a copy of the **ok** button, so the problem should also occur for the ok button, but apparently doesn't.
Differences:
1. hide button is smaller
2. hide button is aligned to *start* instead of *end* (i.e. left instead of right)
3. ok button is invisible in the beginning, while hide button isn't
4. hide button is (unnecessarily) set to become visible once quest fragment is created, while ok button becomes visible later

My best guess is that the problem is *3*: the button might be created before some navigation bar checks are done.
So I'll set it to be invisible at the start and you can tell me whether it helps.

**Comment by tiptoptom** [comment] 2022-05-10 05:28
​

**Comment by tiptoptom** [comment] 2022-05-10 10:51
![grafik](https://user-images.githubusercontent.com/73886169/167612377-68f72493-2512-4717-b987-7ccda438fdcc.png)

**Comment by mnalis** [comment] 2022-05-17 13:36
I seem to recall that the hide button was bigger (and positioned more upward?) in times past, but cannot prove it. It worked without problems back then.

In my my case it does not overlay the navigation buttons directly visually, but seems to be less responsive (e.g. sometimes I need to hit it 2 or 3 times so it registers... I attributed that before just to smaller size, but it could be interference with navigation bar instead. 

![small_Screenshot_20220517_153551_de westnordost streetcomplete h3](https://user-images.githubusercontent.com/156656/168823785-9f051995-4034-437b-9edb-6f0f208c1297.jpg)

**Comment by Helium314** [comment] 2022-05-17 14:41
Initially the size was the same as the `ok` button, but I found it was obstructing too much of the quest form.
Anyway, I hope this is fixed in the latest version.

**Comment by Helium314** [comment] 2022-06-10 07:38
I decided that I do not want to support inventing specific new tags, so I will not implement this.

However, both contact quests support customized element selection via quest settings. You can add `phone:signed != no and ` in front of the selection string and put the rest in brackets.
Then you can tag `phone:signed=no` by editing tags manually from the other answers menu.
Note that you will need https://github.com/Helium314/StreetComplete/commit/9e28ed123f7f27a7059b720de72a05622033d00d for this to work, which is not yet in a published version (soon...).

**Closed by Helium314** 2022-06-10 07:38 UTC
