### ISSUE TITLE
Error message "Too old version" 

### ISSUE THREAD

**Issue by Kalepom** [Helium314/StreetComplete#632] opened 2024-09-01 15:43 UTC
When using the app, an error message keep showing, saying my version is too old to be used. I'm on v58.21 which seems to be the latest. 
![Screenshot_2024-09-01-17-30-40-39_58502f6a51123cb1c0d46bb0f8141155](https://github.com/user-attachments/assets/1d5f8370-d001-4654-9e67-7973b928931a)

**How to Reproduce**
When opening the app, and on every answer

**Expected Behavior**

**Does it happen in normal StreetComplete?**
Only in SCEE 

**Versions affected**
v58.21

**Comment by rusty-snake** [comment] 2024-09-01 15:46
If you found SCEE's GitHub Issues, you can easily find SCEE's GitHub Releases:

![image](https://github.com/user-attachments/assets/a34b2af3-0b8d-438b-8405-2d0c2517355c)

F-Droid is well known for delayed updates. Assuming you installed from there.

**Comment by Kalepom** [comment] 2024-09-01 15:50
Oh, great. Thanks
I usually upload it from F-Droid, where 58.21 is the latest available.

**Comment by jonpsp** [comment] 2024-09-01 16:13
I am not happy to install from GitHub, but I would like to upload my recent changes. Is there an ETA when it will be released?

**Comment by rusty-snake** [comment] 2024-09-01 16:28
You probably have to ask at fdroid but it will be something between today and in a month (that's the usual time fdroid needs).

Given that there is already a [successful build](https://monitor.f-droid.org/builds/log/de.westnordost.streetcomplete.expert/5805) it's likely in the next days.

**Comment by mnalis** [comment] 2024-09-01 22:28
Sorry people, my error - I've set up automation to block that version (as it should be blocked, due to https://github.com/Helium314/SCEE/issues/608#issuecomment-2311284503) expecting F-droid new SCEE release to be published by this Sunday (as it regularly should), but there was delay and I didn't manage to postpone the automation on time due to RL issues that popped up. :sweat: 

Anyway, I've allowed v58.21 to upload again for now, and hopefully f-droid will publish v58.22 in next 5 days (or at least I manage to postpone again if it doesn't). So @jonpsp (and others) you could retry uploading now and hopefully it should work (if not, remove SCEE from recent apps and start it again).

(At least know we know that bad-version-check works properly for SCEE :sweat_smile: )

**Comment by Helium314** [comment] 2024-09-02 18:53
Published on F-Droid already.

Btw the only reason not to download from GitHub when F-Droid still hasn't published would be not trusting me to compile with the code that is in release assets.

**Closed as completed by Helium314** 2024-09-02 18:53 UTC
Labels: bug

**Comment by mnalis** [comment] 2024-09-02 23:47
> Published on F-Droid already.
 
Great! As `58.22` is available on f-droid now too, I've blacklisted `v58.21` now.

> Btw the only reason not to download from GitHub

There are few other reasons, though. For example, one of them is having to know when / how to do that (or just being too lazy), other not wanting to do anything with Microsoft and having all their IP ranges blacklisted, yet another is phone blocking installation from unknown sources and people not being comfortable with allowing Chrome to install `.apk`s etc...

But yes, I get what you mean: since SCEE [is](https://verification.f-droid.org/verified.json) [reproducible build](https://f-droid.org/docs/Reproducible_Builds/), it has same signature so APK from f-droid should[^1] be guaranteed to be the same as APK from GitHub, and Android will allow upgrading one with the other (which it otherwise of course would refuse to do for apps with same id but different signatures)

[^1]: I seem to recall there were some bugs with v1/v2/v3 signatures [noticed by Izzy](https://android.izzysoft.de/articles/named/iod-scan-apkchecks), which might allow app to have some unsigned non-code segments, which could allow it to act differently even with reproducible builds (at that time) by forcing old v1 sigs... But app would have to be written in malicious way in the first place IIRC (It was pretty technical, so I might've misunderstood it)
