### ISSUE TITLE
wrong version in app-release_43.2.apk

### ISSUE THREAD

**Issue by mnalis** [Helium314/StreetComplete#374] opened 2022-05-28 12:09 UTC
Downloading from https://github.com/Helium314/StreetComplete/releases/download/v43.2/app-release_43.2.apk,  one would expect version based on upstream `v43.2`. Instead:

- it identifies itself as `v43.1` in `About` window
- also, clicking on `Version history` in `About`, shows changelog for `v43.2` and `v44.0` too 

Code itself does seems to contain `v44` features like GPX track recording

Perhaps it would be good to base local changes based on upstream `v43.2` (or whichever) git tag (instead on of what happens to be the `master` branch at the moment)?

**Versions affected**
- version from https://github.com/Helium314/StreetComplete/releases/download/v43.2/app-release_43.2.apk

**Comment by Helium314** [comment] 2022-05-28 17:29
This is because I simply take the latest upstream release, and between releases version codes often are not aligned.

Note that h3 version is meant as my personalized version, made available for others. For the new version it's probably best to only do releases in sync with vanilla SC.

**Comment by Helium314** [comment] 2022-05-30 03:08
I just had a look: The specific reason for the version mixup is because of the OAuth problems, where I wanted to quickly release a working version (before the original key was restored).
See https://github.com/Helium314/StreetComplete/commits/my_modifications: latest SC commit mentions v43.2, but v44 changelog was already added earlier. And 43.2 was only added in changelog, but not in version code.

**Comment by Helium314** [comment] 2022-06-18 13:04
While the issue is not solved (I did not change the apk), I'll still close this as it does not occur in the latest release,

**Closed by Helium314** 2022-06-18 13:04 UTC
Labels: bug
