### ISSUE TITLE
Tags of roads under construction cannot being accessed in the app.

### ISSUE THREAD

**Issue by meiphoo7-Mae** [Helium314/StreetComplete#647] opened 2024-09-09 21:13 UTC
Today I marked two existing roads in my area as being under construction. A new store is constructed in that area and this affects the roads. The roads have been fully surveyed and tagged in the past.

AFAICT: every road can be accessed in the app even if there are no quests. For example in the lighting layer every road can be selected and after a few additional taps the associated tags can be seen in the show/edit tags option.
Surprisingly this is no longer possible with these two roads. The roads even loose the color associated with being lit.
In my opinion a road being under construction is perhaps less or not accessible for a certain period of time but the characteristics are not necessarily lost.
Furthermore these two roads are relatively short and in full unobstructed view so it isn't even necessary to access the roads directly to be able to determine the characteristics.

So now if I want to edit the tags of these roads again I'll have to wait until the app asks for a new survey or else I have to use a different app.
I did check in a different app and the existing associated tags have not been deleted so this is apparently about how the app interprets the construction tag.

**How to Reproduce**
Mark a road as being under construction.

**Expected Behavior**
The road  should be clickable in layers like the lighting layer.

**Does it happen in normal StreetComplete?**
It looks like it, but it is harder to proof (because in normal SC there's no show/edit tags option).

**Versions affected**
I think every version so far has been affected by this.

**Comment by mnalis** [comment] 2024-09-09 22:52
> AFAICT: every road can be accessed in the app even if there are no quests

Vast majority of them, but **_not_** all (in default Overlays). 

So yes, it is intended that **Lit overlay** (and other built-in quests/overlays) are only asked on [certain ways](https://github.com/Helium314/SCEE/blob/5994cea0f12c8c020f87a62a198ce5fa51f462f7/app/src/main/java/de/westnordost/streetcomplete/overlays/way_lit/WayLitOverlay.kt#L32C56-L32C65):



https://github.com/Helium314/SCEE/blob/205de3dd3e995d3533073cf6efdb86a3c5fdd1b7/app/src/main/java/de/westnordost/streetcomplete/osm/Highway.kt#L3-L12

And that list intentionally does not include `highway=construction`. 

It makes sense if you think about it; while highway is being constructed, most attributes like lit, surface, cycleways, sidewalks etc. would be wrong until that part of construction was finished. So if you asked them _before_ the construction is completed (e.g. `lit=no` before lamps are installed, `surface=gravel` before asphalt is layed on, etc) it is likely that such incorrect data would remain even when highway was constructed. 

Also, while constructing, those data change very frequently on sections of the road, so you'd have to update them daily. So that is not only waste of time, but also very problematic for other users unless you commit to updating data every day until construction is completed, no matter what. 
Which would be a high ask, of course. So, they are instead not asked until highway construction is completed. 
When highway is marked as constructed, you'll be able to add all of them.

Additionally, if highway was marked as having only _minor reconstructions_ (by choosing [completion date < 6 months](https://github.com/Helium314/SCEE/issues/601#issuecomment-2295300314) in SCEE answer `It is under construction until...`), it will retain its original highway type (e.g. `highway=residential`) and thus you'll be able to continue solving quests/overlays on it.

---

If you however insist on adding extra tags on `highway=construction` (which is bad idea IMHO as explained above), you _can_ create custom overlay which is shown on `highway=*` (or `highway ~ primary|secondary|construction|....`); but again I would discourage using that approach that to add data (but it may be useful for verifying it; e.g. when is construction supposed to be completed if tagged etc).

**Comment by Helium314** [comment] 2024-09-10 14:30
> So now if I want to edit the tags of these roads again I'll have to wait until the app asks for a new survey or else I have to use a different app.

Or you undo your previous edit, or you add a custom overlay as suggested by @mnalis.

The lit overly ignoring roads under construction is certainly intended and not a bug.
Since the road actually remains accessible in the app (_every_ node or way is accessible using a custom overlay), I'll close this as I don't intend to change behavior of the lit overlay. You can ask to include highway=contruction at SC repo, but I don't think such a proposal will be accepted.

**Closed as not planned by Helium314** 2024-09-10 14:30 UTC
