### ISSUE TITLE
Can't switch from one custom overlay to another

### ISSUE THREAD

**Issue by ChildishGiant** [Helium314/StreetComplete#673] opened 2024-10-08 12:25 UTC
**Does it happen in normal StreetComplete?** n/a

**Versions affected**
SCEE v59.1
Android 11

https://github.com/user-attachments/assets/f7d288a4-b421-4563-9a7e-a494de3e1683

When trying to switch from one custom overlay to another nothing happens. A workaround is switching to a built-in one first.

**Comment by rusty-snake** [comment] 2024-10-08 13:06
Duplicate of #655

**Closed as not planned** 2024-10-08 16:52 UTC
Labels: bug
